import { createElement, cache } from 'react'
import { headers } from 'next/headers'
import { betterAuth } from 'better-auth'
import { nextCookies } from 'better-auth/next-js'
import { magicLink } from 'better-auth/plugins'
import { Pool } from 'pg'
import { getEnv } from '@voiceflow/db'

// Phase 21: Better Auth replaces Supabase Auth. Users/sessions live in our own
// Postgres (auth schema, migration 0000); snake_case columns mapped below.
function build() {
  const env = getEnv()
  return betterAuth({
    database: new Pool({ connectionString: env.DATABASE_URL, max: 5, options: '-c search_path=auth' }),
    secret: env.BETTER_AUTH_SECRET,
    baseURL: env.APP_URL,
    user: {
      modelName: 'users',
      fields: { emailVerified: 'email_verified', createdAt: 'created_at', updatedAt: 'updated_at' },
    },
    session: {
      modelName: 'sessions',
      fields: {
        userId: 'user_id',
        expiresAt: 'expires_at',
        ipAddress: 'ip_address',
        userAgent: 'user_agent',
        createdAt: 'created_at',
        updatedAt: 'updated_at',
      },
    },
    account: {
      modelName: 'accounts',
      fields: {
        userId: 'user_id',
        accountId: 'account_id',
        providerId: 'provider_id',
        accessToken: 'access_token',
        refreshToken: 'refresh_token',
        idToken: 'id_token',
        accessTokenExpiresAt: 'access_token_expires_at',
        refreshTokenExpiresAt: 'refresh_token_expires_at',
        createdAt: 'created_at',
        updatedAt: 'updated_at',
      },
    },
    verification: {
      modelName: 'verifications',
      fields: { expiresAt: 'expires_at', createdAt: 'created_at', updatedAt: 'updated_at' },
    },
    // uuid ids generated by Postgres, so auth.users(id) stays the uuid every
    // org_members/admin_users/created_by FK already references.
    advanced: { database: { generateId: 'uuid' } },
    plugins: [
      magicLink({
        expiresIn: 15 * 60,
        storeToken: 'hashed', // a DB leak must not hand out live sign-in links
        sendMagicLink: async ({ email, url }, request) => {
          // Lazy: keeps resend/react-email out of the middleware bundle.
          const [{ sendEmail, brandFrom, emailFrom }, { MagicLinkEmail }, { resolveBrandingForHost, platformBranding }] =
            await Promise.all([import('./email'), import('../emails'), import('./branding')])
          // Phase 27 — the one email we cannot brand from an org, because at
          // sign-in time we do not know which org this address belongs to (it
          // may be several, or none yet). The VANITY HOST is the only signal
          // available, and it is the right one: a reseller's customer requests
          // their link on the reseller's domain, so that is whose product this
          // is. No custom domain → the platform look, which is correct for
          // every direct customer.
          const host = request?.headers?.get('host') ?? null
          const branding = (await resolveBrandingForHost(host)) ?? platformBranding()
          const brand = brandFrom(branding)
          if (
            await sendEmail(
              [email],
              `Your ${brand.productName} sign-in link`,
              createElement(MagicLinkEmail, { url, brand }),
              emailFrom(brand, branding)
            )
          )
            return
          if (process.env.NODE_ENV === 'production') throw new Error('RESEND_API_KEY is not set — sign-in links cannot be sent')
          console.log(`[auth] magic link for ${email}: ${url}`) // dev: no Resend key, click from the log
        },
      }),
      nextCookies(), // must stay last: lets server actions set the session cookie
    ],
  })
}

let _auth: ReturnType<typeof build> | undefined

/** Lazy like getEnv(): `next build` evaluates modules without secrets. */
export function getAuth() {
  return (_auth ??= build())
}

export interface SessionUser {
  id: string
  email: string
}

/** The signed-in user, once per request. Null under DEV_BYPASS_AUTH (no user). */
export const currentUser = cache(async (): Promise<SessionUser | null> => {
  if (process.env.DEV_BYPASS_AUTH === '1') return null
  // headers() FIRST: it marks the route dynamic, so `next build` bails out of
  // prerendering before getAuth() reads env it doesn't have at build time.
  const h = await headers()
  const session = await getAuth().api.getSession({ headers: h })
  return session ? { id: session.user.id, email: session.user.email } : null
})
