// 12 SDS Manager-style calls, deliberately including the ambiguous shapes that broke Jev before.
type T = { role: 'agent' | 'user'; message: string }[]
const a = (m: string) => ({ role: 'agent' as const, message: m })
const u = (m: string) => ({ role: 'user' as const, message: m })
export const TRANSCRIPTS: Record<string, T> = {
  demo_booked: [a('Thank you for calling SDS Manager. How can I help?'), u('We have about 350 safety data sheets in paper binders at two plants. I want a demo.'), a('Happy to set that up. Can I get your name, company and email?'), u('Maria Lopez, Brightcoat Paints, maria.lopez@brightcoat.com'), a('Thanks Maria. Is Tuesday at 2pm Eastern good for the demo?'), u('Yes, Tuesday 2pm works.'), a('Booked for Tuesday 2pm Eastern. You will get a confirmation email.')],
  price_objection: [a('Thank you for calling SDS Manager.'), u('How much is it for around 1,000 SDSs?'), a('For about 1,000 SDSs the published annual price is around $2,064.'), u('Hmm, that is more than we budgeted. Our current vendor is cheaper. I will think about it.'), a('Understood. We also offer free migration and a 30-day trial. Would you like me to send details?'), u('No, not right now. Bye.')],
  support_resolved: [a('SDS Manager, how can I help?'), u('I am a customer. How do I print secondary container labels?'), a('Open the substance, click Labels, choose Secondary container, pick a size and click Print.'), u('Found it, thanks, that worked.'), a('Great, anything else?'), u('No, that is all.')],
  support_escalated: [a('SDS Manager, how can I help?'), u('Our SSO login has been broken since this morning, nobody at our site can log in. This is urgent.'), a('I am sorry. I cannot fix account access on the call. I will pass this to our support team right away. What is your account email?'), u('it@northfab.com. Please hurry.'), a('Done. Support will call you back within the hour.')],
  opt_out: [a('Hi, this is SDS Manager calling about chemical compliance software.'), u('Take me off your list. Do not call this number again.'), a('Understood, I have removed you and you will not be contacted again. Goodbye.')],
  voicemail: [a('Hi, this is SDS Manager calling for the EHS manager.'), u('You have reached the voicemail of Tom Becker. Please leave a message after the tone.'), a('Hi Tom, SDS Manager here, please call us back at your convenience.')],
  hangup: [a('Thank you for calling SDS Manager. How can I help?'), u('Hello?')],
  spam: [a('Thank you for calling SDS Manager.'), u('Congratulations! You have been selected for a free cruise. Press 1 to claim your prize.'), a('This line is for SDS Manager enquiries only. Goodbye.')],
  callback_later: [a('SDS Manager, how can I help?'), u('I am interested but in meetings all day. Can someone call me back tomorrow morning after 9?'), a('Of course. What is your name and number?'), u('Raj Patel, 555 410 2299.'), a('Thanks Raj, I have 555 410 2299. Someone will call you tomorrow after 9am.')],
  vague_curious: [a('Thank you for calling SDS Manager.'), u('What exactly is an SDS?'), a('A Safety Data Sheet describes a chemical\'s hazards, handling, storage and emergency measures. OSHA requires employers to keep them accessible.'), u('Okay. I was just curious. Thanks.')],
  competitor_switch: [a('SDS Manager, how can I help?'), u('We use another vendor and our renewal is next month. Can you migrate our data? We have 3 sites.'), a('Yes, migration from other vendors is free, including your location structure, typically 5 to 7 business days.'), u('Good. Send me info by email: kate@harborlabs.com'), a('I will send the migration details to kate@harborlabs.com.')],
  mixed_intent: [a('Thank you for calling SDS Manager.'), u('Two things. Do you support WHMIS for Canada? And separately my colleague says our QR posters stopped working.'), a('Yes, SDS Manager supports WHMIS. For the QR posters, can you tell me what happens when you scan one?'), u('It says access denied. We might have IP restriction on.'), a('That is likely it. IP restriction blocks access from outside your network. An admin can allow it under Settings.'), u('Maybe. I will check with IT. Not sure.')],
}
